<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoryMap = ProductCategory::pluck('id', 'slug')->toArray();

        $products = [
            // Gemstones
            [
                'category_slug' => 'gemstones',
                'name' => 'Natural Certified Yellow Sapphire (Pukhraj) 4.25 Ratti',
                'slug' => 'natural-certified-yellow-sapphire-pukhraj-4-25-ratti',
                'sku' => 'GEM-PUK-01',
                'short_description' => '100% natural, unheated Ceylon yellow sapphire for Brihaspati (Jupiter) strength, knowledge, and prosperity.',
                'description' => "Natural certified Ceylon Yellow Sapphire (Pukhraj) weighing 4.25 Ratti (approx 3.86 carats). Exhibiting rich lemon yellow color and exceptional transparency.\n\nAstrological Lord: Brihaspati (Jupiter)\nBeneficial for: Dhanu (Sagittarius) and Meena (Pisces) ascendants. Brings wisdom, financial prosperity, marital bliss, and professional success.\n\nEnergization Ceremony: Consecrated at our Vedic ashram with 19,000 chants of the Guru Beeja Mantra. Comes with a Government-approved gemological laboratory testing certificate.",
                'price' => 24500.00,
                'sale_price' => 21999.00,
                'stock' => 5,
                'status' => 'active',
                'is_featured' => true,
                'rating_avg' => 4.9,
                'total_reviews' => 48,
            ],
            [
                'category_slug' => 'gemstones',
                'name' => 'Natural Certified Blue Sapphire (Neelam) 5.15 Ratti',
                'slug' => 'natural-certified-blue-sapphire-neelam-5-15-ratti',
                'sku' => 'GEM-NEL-01',
                'short_description' => 'Premium royal blue Ceylon sapphire certified for Shani (Saturn) pacification and rapid career elevation.',
                'description' => "Royal deep blue natural sapphire from the legendary mines of Ceylon. Untreated and unheated with exquisite clarity.\n\nAstrological Lord: Shani Dev (Saturn)\nBeneficial for: Makar (Capricorn) and Kumbha (Aquarius) ascendants. Worn to ward off sudden calamities, overcome Sade Sati blockages, and achieve massive discipline and authority.\n\nIncludes: Lifetime Authenticity Guarantee and individual Laboratory Origin Certificate.",
                'price' => 38000.00,
                'sale_price' => 34500.00,
                'stock' => 3,
                'status' => 'active',
                'is_featured' => true,
                'rating_avg' => 4.8,
                'total_reviews' => 32,
            ],
            [
                'category_slug' => 'gemstones',
                'name' => 'Natural Untreated Red Coral (Moonga) 6.30 Ratti',
                'slug' => 'natural-untreated-red-coral-moonga-6-30-ratti',
                'sku' => 'GEM-MOO-01',
                'short_description' => 'Italian capsule-shaped deep red coral for Mangal (Mars) vigor, leadership, and vitality.',
                'description' => "Authentic Italian Red Coral (Moonga) of premium oxen-blood hue. Known for its flawless surface and high density.\n\nAstrological Lord: Mangal (Mars)\nBeneficial for: Mesha (Aries) and Vrischika (Scorpio). Mitigates Manglik Dosha effects, boosts physical vitality, confidence, and property acquisition luck.\n\nSanctified with Mars Kavach stotram prior to dispatch.",
                'price' => 8500.00,
                'sale_price' => 6999.00,
                'stock' => 12,
                'status' => 'active',
                'is_featured' => false,
                'rating_avg' => 4.7,
                'total_reviews' => 64,
            ],
            [
                'category_slug' => 'gemstones',
                'name' => 'Natural Zambian Emerald (Panna) 3.85 Ratti',
                'slug' => 'natural-zambian-emerald-panna-3-85-ratti',
                'sku' => 'GEM-PAN-01',
                'short_description' => 'Brilliant deep green natural emerald for Budh (Mercury) eloquence, intellect, and business acumen.',
                'description' => "Vibrant emerald green color stone sourced from the prestigious mines of Zambia. Certified natural beryl.\n\nAstrological Lord: Budh (Mercury)\nBeneficial for: Mithuna (Gemini) and Kanya (Virgo). Sharpens mathematical faculties, communication skills, trading intuition, and diplomatic success.",
                'price' => 18000.00,
                'sale_price' => 15500.00,
                'stock' => 7,
                'status' => 'active',
                'is_featured' => true,
                'rating_avg' => 4.9,
                'total_reviews' => 51,
            ],
            [
                'category_slug' => 'gemstones',
                'name' => 'Certified Hessonite (Gomed) 7.20 Ratti',
                'slug' => 'certified-hessonite-gomed-7-20-ratti',
                'sku' => 'GEM-GOM-01',
                'short_description' => 'Honey-colored Ceylon hessonite for Rahu pacification and removal of confusion.',
                'description' => "Natural honey-colored grossular garnet from Sri Lanka. Unheated and untreated.\n\nAstrological Lord: Rahu (Shadow Planet)\nBeneficial for: Calming overactive thoughts, winning legal disputes, protection from hidden enemies, and foreign travels.",
                'price' => 6200.00,
                'sale_price' => null,
                'stock' => 9,
                'status' => 'active',
                'is_featured' => false,
                'rating_avg' => 4.6,
                'total_reviews' => 27,
            ],

            // Rudraksha
            [
                'category_slug' => 'rudraksha',
                'name' => '5 Mukhi Nepali Rudraksha Mala (108+1 Beads)',
                'slug' => '5-mukhi-nepali-rudraksha-mala-108-plus-1-beads',
                'sku' => 'RUD-5MK-01',
                'short_description' => 'Authentic hand-knotted 108+1 Nepali Rudraksha garland for meditation, Shiva japa, and inner tranquility.',
                'description' => "Premium quality 108+1 five-mukhi Nepali Rudraksha beads strung on strong cotton cord with traditional tassel. Each bead is handpicked for symmetry and clarity of mukhi lines.\n\nRuling Deity: Kalagni Rudra (Lord Shiva)\nBenefits: Enhances mental peace, lowers anxiety, regulates blood pressure, and awakens intuitive awareness. Ideal for daily japa and continuous wearing.",
                'price' => 2499.00,
                'sale_price' => 1899.00,
                'stock' => 40,
                'status' => 'active',
                'is_featured' => true,
                'rating_avg' => 4.9,
                'total_reviews' => 142,
            ],
            [
                'category_slug' => 'rudraksha',
                'name' => 'Certified 7 Mukhi Nepali Rudraksha Bead',
                'slug' => 'certified-7-mukhi-nepali-rudraksha-bead',
                'sku' => 'RUD-7MK-01',
                'short_description' => 'Blessed by Goddess Mahalakshmi to overcome financial constraints and attract good fortune.',
                'description' => "Genuine seven-faced (Saat Mukhi) Rudraksha from Nepal with clear mukhi ridges and high natural density.\n\nRuling Deity: Goddess Mahalakshmi\nRuling Planet: Shani (Saturn)\nBenefits: Removes debt, brings financial stability, protects from financial frauds, and promotes commercial success.",
                'price' => 4200.00,
                'sale_price' => 3600.00,
                'stock' => 15,
                'status' => 'active',
                'is_featured' => true,
                'rating_avg' => 4.8,
                'total_reviews' => 79,
            ],
            [
                'category_slug' => 'rudraksha',
                'name' => 'Genuine 1 Mukhi Half-Moon Rudraksha (Kaju Dana)',
                'slug' => 'genuine-1-mukhi-half-moon-rudraksha-kaju-dana',
                'sku' => 'RUD-1MK-01',
                'short_description' => 'The supreme bead of cosmic consciousness and liberation. Blessed directly by Lord Shiva.',
                'description' => "Natural Ek Mukhi Rudraksha shaped in the revered half-moon form. Highly auspicious for meditation practitioners, leaders, and spiritual seekers.\n\nRuling Deity: Shiva / Paramatman\nRuling Planet: Surya (Sun)\nBenefits: Grants immense willpower, removes past karmic burdens, enhances focus, and creates divine protection.",
                'price' => 7800.00,
                'sale_price' => 6499.00,
                'stock' => 8,
                'status' => 'active',
                'is_featured' => true,
                'rating_avg' => 5.0,
                'total_reviews' => 63,
            ],
            [
                'category_slug' => 'rudraksha',
                'name' => 'Rare 14 Mukhi Deva Mani Rudraksha (Nepal)',
                'slug' => 'rare-14-mukhi-deva-mani-rudraksha-nepal',
                'sku' => 'RUD-14M-01',
                'short_description' => 'The supreme protective bead of Lord Hanuman and Mahadev. Grants visionary foresight.',
                'description' => "Extremely rare fourteen-faced collector bead from high-altitude Nepal trees. Symbolizes the 14 Vidyas and 14 Manus.\n\nRuling Deity: Lord Hanuman\nRuling Planet: Mars and Saturn\nBenefits: Awakening of the third eye (Ajna Chakra), fearlessness, supreme intuition, and invincible protection.",
                'price' => 45000.00,
                'sale_price' => null,
                'stock' => 2,
                'status' => 'active',
                'is_featured' => false,
                'rating_avg' => 5.0,
                'total_reviews' => 14,
            ],

            // Yantras
            [
                'category_slug' => 'yantras',
                'name' => 'Authentic 24K Gold Plated Shree Yantra (6x6 inch)',
                'slug' => 'authentic-24k-gold-plated-shree-yantra-6x6-inch',
                'sku' => 'YAN-SHR-01',
                'short_description' => 'Master cosmic geometry yantra etched on thick brass with pure 24K gold micron plating.',
                'description' => "The Mother of all sacred geometry yantras representing Tripurasundari and Sri Vidya cosmic design. Perfectly etched with 9 interlocking triangles, 43 sub-triangles, and dual lotus petals.\n\nPlacement: North-East (Ishanya) corner of home, office, or puja altar.\nBenefits: Amplifies positive vibrations, dissolves vastu doshas, and magnetizes prosperity and peace.",
                'price' => 3500.00,
                'sale_price' => 2850.00,
                'stock' => 25,
                'status' => 'active',
                'is_featured' => true,
                'rating_avg' => 4.9,
                'total_reviews' => 110,
            ],
            [
                'category_slug' => 'yantras',
                'name' => 'Pure Copper Kuber Yantra (Embossed 4x4 inch)',
                'slug' => 'pure-copper-kuber-yantra-embossed-4x4-inch',
                'sku' => 'YAN-KUB-01',
                'short_description' => 'Energized copper plate inscribed with Lord Kuber sacred magic square for wealth conservation.',
                'description' => "Heavy-gauge pure copper sheet featuring the authentic 3x3 magic square totaling 72 in every row and column, dedicated to Lord Kubera.\n\nBenefits: Eliminates unwarranted expenditure, safeguards assets, and blesses business owners with consistent cashflow.",
                'price' => 1450.00,
                'sale_price' => 1199.00,
                'stock' => 35,
                'status' => 'active',
                'is_featured' => false,
                'rating_avg' => 4.7,
                'total_reviews' => 84,
            ],
            [
                'category_slug' => 'yantras',
                'name' => 'Mahamrityunjaya Kavach Yantra (Pure Copper)',
                'slug' => 'mahamrityunjaya-kavach-yantra-pure-copper',
                'sku' => 'YAN-MRY-01',
                'short_description' => 'Lord Shiva life-preserving yantra for relief from prolonged illnesses and acute planetary afflictions.',
                'description' => "Consecrated with the sacred Tryambakam mantra chanted 1008 times. Formed on heavy virgin copper.\n\nBenefits: Radiates protective prana against chronic sickness, sudden accidents, and severe Maraka dasha periods.",
                'price' => 1800.00,
                'sale_price' => null,
                'stock' => 18,
                'status' => 'active',
                'is_featured' => false,
                'rating_avg' => 4.8,
                'total_reviews' => 46,
            ],

            // Puja Essentials
            [
                'category_slug' => 'puja-essentials',
                'name' => 'Organic Guggal & Loban Vedic Dhoop Batti (Set of 4 Boxes)',
                'slug' => 'organic-guggal-and-loban-vedic-dhoop-batti-set-of-4-boxes',
                'sku' => 'PUJ-DHP-01',
                'short_description' => '100% natural, charcoal-free dhoop sticks made with Himalayan herbs, cow ghee, and sacred resins.',
                'description' => "Crafted strictly according to Ayurvedic treatise using wild Himalayan Commiphora mukul (Guggal), Boswellia (Loban), and A2 desi cow ghee. Free of artificial fragrances and toxic charcoal.\n\nBenefits: Purifies home energy, clears negative planetary air, and sets a tranquil atmosphere for prayer.",
                'price' => 699.00,
                'sale_price' => 549.00,
                'stock' => 60,
                'status' => 'active',
                'is_featured' => false,
                'rating_avg' => 4.9,
                'total_reviews' => 95,
            ],
            [
                'category_slug' => 'puja-essentials',
                'name' => 'Solid Brass Akhand Jyot Diya with Borosilicate Chimney',
                'slug' => 'solid-brass-akhand-jyot-diya-with-borosilicate-chimney',
                'sku' => 'PUJ-DIY-01',
                'short_description' => 'Heavy brass perennial lamp with windproof glass cover for uninterrupted 24-hr Navratri pujas.',
                'description' => "Engineered with thick high-grade brass and a heat-resistant borosilicate glass enclosure. Specially designed oil cup maintains continuous flame without smoking for up to 36 hours.\n\nIdeal for Navratri, Diwali, and continuous temple worship.",
                'price' => 1850.00,
                'sale_price' => 1499.00,
                'stock' => 20,
                'status' => 'active',
                'is_featured' => false,
                'rating_avg' => 4.8,
                'total_reviews' => 52,
            ],

            // Reports & Texts
            [
                'category_slug' => 'reports-texts',
                'name' => 'Personalized 55-Page Deluxe Janam Kundli & Dasha Report',
                'slug' => 'personalized-55-page-deluxe-janam-kundli-and-dasha-report',
                'sku' => 'REP-KUN-01',
                'short_description' => 'Comprehensive lifetime astrology forecast including divisional charts (D1 to D60), Vimshottari dasha, and custom remedies.',
                'description' => "Receive an exhaustive 55+ page personalized Vedic astrological horoscope prepared based on exact planetary ephemeris (Lahiri Ayanamsha).\n\nIncludes:\n- Detailed Lagna, Navamsha, and Dashamsha charts\n- 120-year Vimshottari Mahadasha and Antardasha timeline\n- Sade Sati dates, phases, and specific mitigation remedies\n- Recommended gemstone, rudraksha, and gotra mantras\n\nDelivered as high-resolution PDF with optional bound hardcopy.",
                'price' => 1299.00,
                'sale_price' => 999.00,
                'stock' => 100,
                'status' => 'active',
                'is_featured' => true,
                'rating_avg' => 4.9,
                'total_reviews' => 210,
            ],
            [
                'category_slug' => 'reports-texts',
                'name' => 'Annual Varshphal (Solar Return) Detailed Forecast 2026-2027',
                'slug' => 'annual-varshphal-solar-return-detailed-forecast-2026-2027',
                'sku' => 'REP-VAR-01',
                'short_description' => 'Month-by-month Tajika solar return horoscope with Muntha analysis and critical timing dates.',
                'description' => "Calculated at the precise moment when the Sun returns to its exact natal zodiac degree. The premier Vedic system for planning upcoming business investments, career shifts, and family events.\n\nIncludes Mudda Dasha, Patyayini Dasha, and Sahams analysis.",
                'price' => 1599.00,
                'sale_price' => 1199.00,
                'stock' => 100,
                'status' => 'active',
                'is_featured' => false,
                'rating_avg' => 4.7,
                'total_reviews' => 67,
            ],

            // Crystals & Malas
            [
                'category_slug' => 'crystals-malas',
                'name' => 'Natural Sphatik (Quartz Crystal) Japa Mala (108 Beads)',
                'slug' => 'natural-sphatik-quartz-crystal-japa-mala-108-beads',
                'sku' => 'CRY-SPH-01',
                'short_description' => 'Hand-cut diamond faceted natural ice quartz rosary for calming the nervous system and Chandra mantra chanting.',
                'description' => "Pure, cool crystalline quartz beads mined in the Himalayas. Faceted cut reflects ambient light into rainbow spectra.\n\nRuling Deity: Goddess Saraswati & Gayatri\nRuling Planet: Chandra (Moon) & Venus\nBenefits: Enhances mental concentration, absorbs body heat, relieves stress, and accelerates mantra siddhi.",
                'price' => 1650.00,
                'sale_price' => 1299.00,
                'stock' => 30,
                'status' => 'active',
                'is_featured' => true,
                'rating_avg' => 4.9,
                'total_reviews' => 88,
            ],
            [
                'category_slug' => 'crystals-malas',
                'name' => 'Original Vrindavan Tulsi Japa Mala with Silver Caps',
                'slug' => 'original-vrindavan-tulsi-japa-mala-with-silver-caps',
                'sku' => 'CRY-TLS-01',
                'short_description' => 'Sanctified black basil holy wood rosary adorned with pure 925 sterling silver filigree caps.',
                'description' => "Handcrafted from aged Krishna Tulsi timber grown in holy Vrindavan Dham. Each bead is individually encased in silver capping with an ornamental Meru bead.\n\nBenefits: Imparts divine sattvic consciousness, purifies the subtle body aura, and invokes Lord Vishnu and Krishna presence.",
                'price' => 2200.00,
                'sale_price' => 1850.00,
                'stock' => 15,
                'status' => 'active',
                'is_featured' => false,
                'rating_avg' => 5.0,
                'total_reviews' => 56,
            ],
        ];

        foreach ($products as $pData) {
            $catSlug = $pData['category_slug'];
            unset($pData['category_slug']);

            $pData['category_id'] = $categoryMap[$catSlug] ?? null;

            Product::updateOrCreate(['sku' => $pData['sku']], $pData);
        }
    }
}
